### ISSUE TITLE
withConnection is not async

### ISSUE THREAD

**Issue by polc** [musicglue/pg-ts#20]
Hello, thanks for these bindings. I've some problem using `withConnection`, which look non async, for example here the `console.log` is never displayed : 

```typescript
import {Option, none} from "fp-ts/lib/Option";
import {Task} from "fp-ts/lib/Task";
import {identity} from "fp-ts/lib/function";
import {camelCasedQueries, ConnectionPool, SQL, makeConnectionPool} from "pg-ts";
import {User} from "./models/user";

const { queryOneOrNone } = camelCasedQueries;
type FindUserByEmail = (email: string) => Task<Option<User>>;

namespace PostgreSQL {
  export const findUserByEmail = (pool: ConnectionPool): FindUserByEmail => email => pool
    .withConnection(queryOneOrNone(User, SQL(`select * from users where email = $1`, email)))
    .fold(() => none, identity)
  ;
}

const connectionPool = makeConnectionPool({ onError: console.error, connectionString: process.env.DATABASE_URI });
const findUserByEmail = email => connectionPool.chain(connectionPool => PostgreSQL.findUserByEmail(connectionPool)(email));

console.log('Hello world !'); // this log is never dispatched
```

If I don't call `run()`, nothing should happen, right?  Maybe you have an idea about why this is happening? Thanks !

**Comment by nikcorg** [comment]
Hi @polc,

As your `console.log` invocation should happen at module import time, even if `withConnection` was synchronous (which it isn't), you should always see the output.

Might it be a problem in your compilation settings? Maybe you are stripping out calls to console.log or something similar. Can you see any compilation errors?

However, your usage of `SQL` is incorrect. The correct usage is:

```
SQL`select * from users where email = ${email}`
```

The tagged template literal will replace interpolated bits with placeholders for you.

**Comment by polc** [comment]
Actually I just found that my script is running out of memory after executing during 60s. I don't know if the fact that I'm using `ts-node` change something. Anyway, if I stop using `withConnection` everything is working fine again. 

I've made a reproduction repo if you have time to look at it : https://github.com/polc/out-of-memory/blob/master/src/main.ts

**Comment by polc** [comment]
OK it was a problem of the `fp-ts` version which was `1.10.0` instead of the required `1.8.0` by this package. Thanks for the help!
