### ISSUE TITLE
Documentation or fp-ts 2.0+

### ISSUE THREAD

**Issue by baetheus** [musicglue/pg-ts#28]
Any chance of documentation or an update to fp-ts 2.0+?

**Comment by nikcorg** [comment]
Updating at some point is something I want to get done, but there isn't currently time available for it. I cannot say when there will be, but I'm hoping during this year. There is however a [fork by one of the original authors](https://github.com/leemhenson/pg-ts) that has been updated to fp-ts 2.0. You may want to have a look at that one in the mean time.  

Sadly, the same (poor) lack of time excuse goes for the documentation. You'll have to infer usage from the tests for now. Hopefully both issues can be addressed in one fell swoop.
