### ISSUE TITLE
7.0 update?

### ISSUE THREAD

**Issue by avindra** [musicglue/pg-ts#7]
Is there work planned for upgrading the `node-postgres` dependency to the `7.x` release?

Also, generally, is there a comparison of what this does compared to `@types/pg`?

**Comment by jgwmaxwell** [comment]
Hi @avindra, sorry for the slow reply. We're working on a release that includes 7.0 at the moment, and replaces the pg-pool implementation with a generic-pool based one that will allow stack-based queue operation.

In terms of the comparison with [node-postgres](https://github.com/brianc/node-postgres), this library uses it underneath to deliver connectivity, and really offers an opinionated way of consuming that project.  You absolutely do not need this, however it you've got a reasonably complex application then it can be a nice way of rationalising some of the complexity.
